### ISSUE TITLE
[Bug] Plugin wont load 

### ISSUE THREAD

**Issue by TheOnlyRealTGS** [pgmann/SpectatorPlus#50]
I'm getting this error again on plugin load:
http://pastebin.com/0xtfijVw
I've created a zip of my spigot jar, and folders: https://mega.nz/#!sgRHXZqB!Y-hAgUBtMps_6HhJy3_ysWnl3u806bjEyNbNS-r3ymo

**Comment by pgmann** [comment]
- How did you load it? By starting the server?
- Was it the first time to load the server or was there config already?

**Comment by pgmann** [comment]
Your download's been removed by the way, it would seem.

**Comment by TheOnlyRealTGS** [comment]
1. Starting the server
2. Config was there already.
I have re-uploaded it https://mega.nz/#!sgRHXZqB!Y-hAgUBtMps_6HhJy3_ysWnl3u806bjEyNbNS-r3ymo

**Comment by pgmann** [comment]
Assigning @AmauryCarrade to fix this - just located the problem but I couldn't work out how to fix it...

When the plugin loads and the serialized Arenas are read from setup.yml, any Arena that still exists in the setup.yml, but **the arena's world file is deleted** will cause this error. We need to detect this (i.e. if corner1 has a `null` value) and print a message to the console saying "Skipping arena <name> because its world no longer exists."
I can't figure out how to do this so I'd appreciate if you'd do it please ;)

**Comment by TheOnlyRealTGS** [comment]
Hey, thank you so much for taking time to find the problem!
However as far as I can see none of my worlds have been deleted.

**Comment by pgmann** [comment]
Check your setup.yml - it's in a readable format. I saw a world called
Lobby2.0 (by the way, the dot might break the plugin) as well as loads of
game worlds...
For me I could reproduce your error exactly by renaming my world.

**Comment by TheOnlyRealTGS** [comment]
Well, Lobby2.0 is a unfortunate name I'll give you that, but it definitely
exists.

2015-05-27 20:18 GMT+02:00 pgmann <notifications@github.com>:

**Comment by pgmann** [comment]
Save a backup then try deleting one arena at a time from the setup.yml
file. If the plugin loads, problem solved!

**Comment by TheOnlyRealTGS** [comment]
I made it load by deleting the last arena, we'll see if it still works in a few days.

**Comment by pgmann** [comment]
Seems that fixed your problem? Would I be right in thinking that?
If so, we just need @AmauryCarrade to implement the auto-fix to prevent arenas being loaded when their world no longer exists.

**Comment by TheOnlyRealTGS** [comment]
No, after I restarted the server the problem occured again :(

**Comment by pgmann** [comment]
Aww... did you make any more arenas after deleting that one?

**Comment by TheOnlyRealTGS** [comment]
Nope.

**Comment by AmauryCarrade** [comment]
I will review and fix this as soon as possible. This said, I'm pretty busy this time but I'll do that when possible.

**Comment by TheOnlyRealTGS** [comment]
Sounds good!

2015-06-04 19:22 GMT+02:00 Amaury Carrade <notifications@github.com>:

**Comment by AmauryCarrade** [comment]
@TheOnlyRealTGS Can you try [with this](http://jenkins.carrade.eu/job/SpectatorPlus/lastSuccessfulBuild/artifact/SpectatorPlus/target/SpectatorPlus-B2.1.jar)? It should autofix the arena file by using the default world if a world is missing. Can you try that and send me the log?

**Comment by pgmann** [comment]
Hmm, only problem with that is the arena shouldn't actually be in the
default world... But fine for testing ;)

**Comment by AmauryCarrade** [comment]
If the default world is null, it means that there isn't any world in the server, a situation that couldn't happens in a normal state.

**Comment by pgmann** [comment]
Yes, but imagine this:

create arena 'test' in 'world'
Stop server -> edit server.properties
'world' -> rename -> 'world2'
delete 'world' folder
Start server -> error

Hopefully that makes sense?

**Comment by AmauryCarrade** [comment]
No, because when the server will restart, the « world2 » will be generated, and this world will be returned by Bukkit.getWorlds().get(0).
So this will not be a problem, the arena will be switched to world2.

This said, we may also delete the arena in these cases. I don't know what the better solution is. The first one (arena moved to the default world) allows the server owner to edit the arena.yml file to change the name of the world when it's back. That's why I implemented this solution.

5 juin 2015 13:59 "pgmann"  a écrit:

Yes, but imagine this:

create arena 'test' in 'world'
Stop server -> edit server.properties
'world' -> rename -> 'world2'
delete 'world' folder
Start server -> error

Hopefully that makes sense?

**Comment by pgmann** [comment]
My idea was to simply ignore the invalid arena, don't load it and log a
message to the console telling the server owner to fix it manually. Sound
good?

**Comment by AmauryCarrade** [comment]
Sounds good, if we don't remove it from the config file.

5 juin 2015 14:05 "pgmann"  a écrit:

My idea was to simply ignore the invalid arena, don't load it and log a
message to the console telling the server owner to fix it manually. Sound
good?

**Comment by pgmann** [comment]
Okay, hopefully you do better than my test implementation... It failed so
bad I reset the branch :P

Remember to log a console message too: "Arena <name> couldn't be loaded as
its world was not found."

**Comment by AmauryCarrade** [comment]
@pgmann @TheOnlyRealTGS Implemented, see above (if you are on GitHub) or the Jenkins builds.

**Comment by pgmann** [comment]
Great! Now we just need @TheOnlyRealTGS to test it.

**Comment by pgmann** [comment]
P.s. lol my ci server died trying to build it :D

**Comment by AmauryCarrade** [comment]
*Your* CI server? You changed the CI server? That's why the builds are no longer automatically done on my Jenkins server?

**Comment by pgmann** [comment]
Yes, I was experimenting with openshift and discovered I could host a CI
server on it on a diy cartridge.
See it here: http://ci.pgmann.cf/
I wanted to see if it was up to much, but if it keeps crashing I'll just go
back to your server (it's really just a test to see if it works for a
while).

**Comment by AmauryCarrade** [comment]
No problem eh, of course, but you can have two hooks, one for each server, so both of them build the plugin :) .

**Comment by pgmann** [comment]
Hmm... I couldn't get that to work... As far as I can see only 1 service of
the type "Jenkins (Github)" can be active at a time...

**Comment by AmauryCarrade** [comment]
Oh, in this case... Weired, but ok.

**Comment by TheOnlyRealTGS** [comment]
So latest build (124), testing ASAP.

**Comment by pgmann** [comment]
Fixed? Or have you not had time to test yet?

**Comment by TheOnlyRealTGS** [comment]
Haven't had time yet.

2015-06-06 20:30 GMT+02:00 pgmann <notifications@github.com>:

**Comment by TheOnlyRealTGS** [comment]
So, this happened.. http://pastebin.com/FrsQL8cz

**Comment by pgmann** [comment]
Hmm, interesting... Did any of the arenas load? (Try /spec arena list)

**Comment by TheOnlyRealTGS** [comment]
Looks like this:
07:07:59 [INFO]           ~~ Arenas ~~
07:07:59 [INFO] KitBattle - Lobby: 186;76;307
07:07:59 [INFO] HungerGames3 - Lobby: -1;13;0
07:07:59 [INFO] HungerGames14 - Lobby: 15;69;24
07:07:59 [INFO] HungerGames9 - Lobby: 475;25;723
07:07:59 [INFO] HungerGames15 - Lobby: 659;10;-1881
07:07:59 [INFO] HungerGames4 - Lobby: 0;37;-3
07:07:59 [INFO] HungerGames12 - Lobby: -4565;60;592
07:07:59 [INFO] HungerGames5 - Lobby: 0;32;0
07:07:59 [INFO] HungerGames8 - Lobby: 1;25;5
07:07:59 [INFO] HungerGames7 - Lobby: 15;72;24
07:07:59 [INFO] HungerGames11 - Lobby: 1;103;0
07:07:59 [INFO] HungerGames2 - Lobby: 0;21;0
07:07:59 [INFO] HungerGames13 - Lobby: 24;75;-20
07:07:59 [INFO] HungerGames1 - Lobby: -1577;60;-611
07:07:59 [INFO] HungerGames6 - Lobby: 29;74;48
07:07:59 [INFO] HungerGames10 - Lobby: -1218;64;186
But teleporting to any arenas teleports me to (right? I think) cords, but the wrong world (the one that the main lobby is in, (Lobby2.0).

**Comment by pgmann** [comment]
Okay...
Hmm, we'll have to look at the code again :D
Must be detecting all arenas as not having a world...

**Comment by TheOnlyRealTGS** [comment]
I guess so. Thanks for your continued support! :+1:

**Comment by pgmann** [comment]
Give it a test.
Build 7 on my CI server: http://ci.pgmann.cf/job/SpectatorPlus/lastSuccessfulBuild/artifact/SpectatorPlus/target/SpectatorPlus-B2.1.jar

**Comment by pgmann** [comment]
Ping @TheOnlyRealTGS ;)

**Comment by TheOnlyRealTGS** [comment]
Seems like the plugin force changes the correct original world name to the world where the lobby is.

**Comment by pgmann** [comment]
Hmm... can you give me steps to reproduce that?

**Comment by TheOnlyRealTGS** [comment]
It seems all my world names changed, I changed them back. but I think it works now. Will report back if it doesn't.

**Comment by pgmann** [comment]
Okay, glad to hear :)

**Comment by TheOnlyRealTGS** [comment]
Thanks for helping too! :)

2015-06-17 19:37 GMT+02:00 pgmann <notifications@github.com>:

**Comment by TheOnlyRealTGS** [comment]
Okay, after I restarted it said "KitPvP" doesn't exist, and therefore it didn't load the arena.
What now?

**Comment by pgmann** [comment]
Please include a bit more detail... do you have the world folder KitPvP (case sensitive) still in your server folder? Did you change anything between server loads? Do you have any plugins that might have changed the world? And, can you travel to the KitPvP world in game when SpectatorPlus says it can't be found?
Also, try using /spec reload or restart the server to see if it always says this or just once.

**Comment by TheOnlyRealTGS** [comment]
>Please include a bit more detail... do you have the world folder KitPvP (case sensitive) still in your server folder?

Yep

>Did you change anything between server loads?
Don't think so 

>Do you have any plugins that might have changed the world? 
No

>And, can you travel to the KitPvP world in game when SpectatorPlus says it can't be found?
Yep

And I already restarted the server, and /spec reload fixed it.

So again, maybe you need to run the check for arenas, post-enable?

**Comment by pgmann** [comment]
Perhaps. Can you try a restart (maybe even a couple?) and see if that breaks anything again? That would confirm the plugin is checking which worlds are loaded too soon.

**Comment by TheOnlyRealTGS** [comment]
My server will restart in 12 hours, can't do it now while people are online.

**Comment by TheOnlyRealTGS** [comment]
Server restarted same issue. /spec reload fixed it.

**Comment by pgmann** [comment]
Okay, I guess we've nailed down the bug then. I'll work on a fix.

Out of interest, was it the exact same world, KitPvP?

**Comment by TheOnlyRealTGS** [comment]
Yep. Sounds good!
Den 23/06/2015 17.32 skrev "pgmann" <notifications@github.com>:

**Comment by TheOnlyRealTGS** [comment]
So I deleted all arenas exept one, and downgraded to 2.1
Getting this error:

2015-16-07 17:51:46 [INFO] [SpectatorPlus] Enabling SpectatorPlus v2.1
2015-16-07 17:51:46 [ERROR] Error occurred while enabling SpectatorPlus v2.1 (Is it up to date?)
java.lang.NullPointerException
        at com.pgcraft.spectatorplus.Arena.serialize(Arena.java:88) ~[?:?]
        at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSerializable.representData(YamlRepresenter.java:33) ~[spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-6d16e64-bf4818b]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:94) ~[spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-6d16e64-bf4818b]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:156) ~[spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-6d16e64-bf4818b]
        at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:304) ~[spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-6d16e64-bf4818b]
        at org.bukkit.configuration.file.YamlRepresenter$RepresentConfigurationSection.representData(YamlRepresenter.java:23) ~[spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-6d16e64-bf4818b]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:94) ~[spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-6d16e64-bf4818b]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representMapping(BaseRepresenter.java:156) ~[spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-6d16e64-bf4818b]
        at org.yaml.snakeyaml.representer.SafeRepresenter$RepresentMap.representData(SafeRepresenter.java:304) ~[spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-6d16e64-bf4818b]
        at org.yaml.snakeyaml.representer.BaseRepresenter.representData(BaseRepresenter.java:94) ~[spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-6d16e64-bf4818b]
        at org.yaml.snakeyaml.representer.BaseRepresenter.represent(BaseRepresenter.java:64) ~[spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-6d16e64-bf4818b]
        at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:242) ~[spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-6d16e64-bf4818b]
        at org.yaml.snakeyaml.Yaml.dumpAll(Yaml.java:206) ~[spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-6d16e64-bf4818b]
        at org.yaml.snakeyaml.Yaml.dump(Yaml.java:181) ~[spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-6d16e64-bf4818b]
        at org.bukkit.configuration.file.YamlConfiguration.saveToString(YamlConfiguration.java:40) ~[spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-6d16e64-bf4818b]
        at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:103) ~[spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-6d16e64-bf4818b]
        at com.pgcraft.spectatorplus.ConfigAccessor.saveConfig(ConfigAccessor.java:80) ~[?:?]
        at com.pgcraft.spectatorplus.SpectatorPlus.setSpectatorMode(SpectatorPlus.java:1229) ~[?:?]
        at com.pgcraft.spectatorplus.SpectatorPlus.reloadConfig(SpectatorPlus.java:1146) ~[?:?]
        at com.pgcraft.spectatorplus.SpectatorPlus.onEnable(SpectatorPlus.java:135) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-6d16e64-bf4818b]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-6d16e64-bf4818b]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-6d16e64-bf4818b]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:356) [spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-6d16e64-bf4818b]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316) [spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-6d16e64-bf4818b]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-6d16e64-bf4818b]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-6d16e64-bf4818b]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-6d16e64-bf4818b]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-6d16e64-bf4818b]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:524) [spigot-1.8.7-R0.1-SNAPSHOT-latest.jar:git-Spigot-6d16e64-bf4818b]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]

**Comment by TheOnlyRealTGS** [comment]
Hey, a month has passed, I'm wondering if this plugin is still alive? :)

**Comment by pgmann** [comment]
Meh, sort of... I'm developing an app for Android at the moment, but I'll
probably work on this plugin again before too long...

**Comment by TheOnlyRealTGS** [comment]
Okay, I wish you luck with the app!

**Comment by pgmann** [comment]
Thanks! If you want to see it so far, check out the project page of Group
Games on my website (http://pgmann.cf) - it may not look like much but it's
taken ages ;)

**Comment by TheOnlyRealTGS** [comment]
Really good job!
I myself coded a website from scratch too a few days ago! It's much better
than using templates, but ofc. isn't as pretty :)

2015-08-16 12:00 GMT+02:00 pgmann <notifications@github.com>:

**Comment by TheOnlyRealTGS** [comment]
Just an update, this is still happening.

**Comment by AmauryCarrade** [comment]
The way arenas are stored was completely rewrote in the last version (not published yet), so this is probably no longer a problem. Reopen if needed when tested with the new version (when it will be published of course).
