### ISSUE TITLE
NullPointerException while disabling SpectatorPlus

### ISSUE THREAD

**Issue by TiTo-418** [pgmann/SpectatorPlus#66]
```
[08:50:48 ERROR]: Error occurred while disabling SpectatorPlus v3.0 (Is it up to date?)
java.lang.NullPointerException
        at com.pgcraft.spectatorplus.zlib.components.gui.Gui.update(Gui.java:192) ~[?:?]
        at com.pgcraft.spectatorplus.spectators.Spectator.setSpectating(Spectator.java:161) ~[?:?]
        at com.pgcraft.spectatorplus.spectators.Spectator.setSpectating(Spectator.java:135) ~[?:?]
        at com.pgcraft.spectatorplus.spectators.Spectator.setSpectating(Spectator.java:112) ~[?:?]
        at com.pgcraft.spectatorplus.SpectatorPlus.onDisable(SpectatorPlus.java:130) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:364) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.disablePlugins(CraftServer.java:336) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.stop(MinecraftServer.java:460) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:593) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_74]
```

Lastest build

**Comment by pgmann** [comment]
Does this happen every time you disable the plugin (i.e. stop your server), or was it a one off?

**Comment by pgmann** [comment]
@AmauryCarrade, looks like zLib needs a `!= null` check [here](https://github.com/zDevelopers/zLib/blob/master/src/main/java/fr/zcraft/zlib/components/gui/Gui.java#L192).

**Comment by AmauryCarrade** [comment]
Indeed. I'll fix that later today (I'm far from any computer right now).

Le 7 mai 2016 20:43:19 GMT+02:00, pgmann <notifications@github.com> a écrit :
>@AmauryCarrade, looks like zLib needs a `!= null` check
>[here](https://github.com/zDevelopers/zLib/blob/master/src/main/java/fr/zcraft/zlib/components/gui/Gui.java#L192).
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/pgmann/SpectatorPlus/issues/66#issuecomment-217661088

—
Message envoyé depuis un appareil mobile. Veuillez excuser ma brièveté.

**Comment by pgmann** [comment]
@TiTo-418, this has just been fixed. Please test with the latest build from Jenkins :)

**Comment by TiTo-418** [comment]
Works as expected
