### ISSUE TITLE
Invalid slot ID in 1.9

### ISSUE THREAD

**Issue by TiTo-418** [pgmann/SpectatorPlus#71]
I'm pretty sure it's the shield slot

```
[20:47:43 WARN]: [SpectatorPlus] Task #242 for SpectatorPlus v3.0 generated an exception
java.lang.IllegalArgumentException: Illegal slot ID
        at com.pgcraft.spectatorplus.zlib.components.gui.ActionGui.action(ActionGui.java:175) ~[?:?]
        at com.pgcraft.spectatorplus.guis.PlayerInventoryGUI.onUpdate(PlayerInventoryGUI.java:103) ~[?:?]
        at com.pgcraft.spectatorplus.zlib.components.gui.GuiBase.update(GuiBase.java:79) ~[?:?]
        at com.pgcraft.spectatorplus.zlib.components.gui.InventoryGui.update(InventoryGui.java:81) ~[?:?]
        at com.pgcraft.spectatorplus.zlib.components.gui.ActionGui.update(ActionGui.java:282) ~[?:?]
        at com.pgcraft.spectatorplus.zlib.components.gui.GuiBase.open(GuiBase.java:139) ~[?:?]
        at com.pgcraft.spectatorplus.zlib.components.gui.InventoryGui.open(InventoryGui.java:117) ~[?:?]
        at com.pgcraft.spectatorplus.zlib.components.gui.Gui$1.run(Gui.java:112) ~[?:?]
        at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16]
        at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16]
        at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:734) [spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16]
        at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16]
        at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16]
        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_74]
```

**Comment by pgmann** [comment]
Issue with zLib.

@AmauryCarrade

**Comment by AmauryCarrade** [comment]
Not an issue with zLib, an issue with SP.

I still take this.

**Comment by AmauryCarrade** [comment]
NPE removed bug the inventory is still pretty unusable because it does not opens.

I added some stacktraces of the openings and closings (last one is my logout; I never closed the GUI manually) with a code like this:
```java
try { throw new Exception(); } catch (Exception e) { e.printStackTrace(); }
```
and I got this:
```
[17:27:24 ERROR]: [SpectatorPlus] Inventory opened
java.lang.Exception
        at com.pgcraft.spectatorplus.listeners.GuiUpdatesListener.on(GuiUpdatesListener.java:124) [SpectatorPlus-B3.0-SNAPSHOT.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:748) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at net.minecraft.server.v1_9_R1.EntityPlayer.openContainer(EntityPlayer.java:697) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at org.bukkit.craftbukkit.v1_9_R1.entity.CraftHumanEntity.openInventory(CraftHumanEntity.java:192) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at com.pgcraft.spectatorplus.zlib.components.gui.InventoryGui.open(InventoryGui.java:118) [SpectatorPlus-B3.0-SNAPSHOT.jar:?]
        at com.pgcraft.spectatorplus.zlib.components.gui.Gui$1.run(Gui.java:112) [SpectatorPlus-B3.0-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
[17:27:24 ERROR]: [SpectatorPlus] Inventory closed
java.lang.Exception
        at com.pgcraft.spectatorplus.listeners.GuiUpdatesListener.on(GuiUpdatesListener.java:130) [SpectatorPlus-B3.0-SNAPSHOT.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:871) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1628) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:739) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at net.minecraft.server.v1_9_R1.EntityPlayer.openContainer(EntityPlayer.java:697) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at org.bukkit.craftbukkit.v1_9_R1.entity.CraftHumanEntity.openInventory(CraftHumanEntity.java:192) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at com.pgcraft.spectatorplus.zlib.components.gui.InventoryGui.open(InventoryGui.java:118) [SpectatorPlus-B3.0-SNAPSHOT.jar:?]
        at com.pgcraft.spectatorplus.zlib.components.gui.Gui$1.run(Gui.java:112) [SpectatorPlus-B3.0-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
[17:27:24 ERROR]: [SpectatorPlus] Inventory opened
java.lang.Exception
        at com.pgcraft.spectatorplus.listeners.GuiUpdatesListener.on(GuiUpdatesListener.java:124) [SpectatorPlus-B3.0-SNAPSHOT.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:748) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at net.minecraft.server.v1_9_R1.EntityPlayer.openContainer(EntityPlayer.java:697) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at org.bukkit.craftbukkit.v1_9_R1.entity.CraftHumanEntity.openInventory(CraftHumanEntity.java:192) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at com.pgcraft.spectatorplus.zlib.components.gui.InventoryGui.open(InventoryGui.java:118) [SpectatorPlus-B3.0-SNAPSHOT.jar:?]
        at com.pgcraft.spectatorplus.zlib.components.gui.Gui$1.run(Gui.java:112) [SpectatorPlus-B3.0-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
[17:27:24 ERROR]: [SpectatorPlus] Inventory closed
java.lang.Exception
        at com.pgcraft.spectatorplus.listeners.GuiUpdatesListener.on(GuiUpdatesListener.java:130) [SpectatorPlus-B3.0-SNAPSHOT.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:871) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at net.minecraft.server.v1_9_R1.EntityPlayer.closeInventory(EntityPlayer.java:838) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at org.bukkit.craftbukkit.v1_9_R1.entity.CraftHumanEntity.closeInventory(CraftHumanEntity.java:375) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at com.pgcraft.spectatorplus.zlib.components.gui.InventoryGui$1.run(InventoryGui.java:139) [SpectatorPlus-B3.0-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
[17:29:27 INFO]: AmauryPi lost connection: Disconnected
[17:29:27 ERROR]: [SpectatorPlus] Inventory closed
java.lang.Exception
        at com.pgcraft.spectatorplus.listeners.GuiUpdatesListener.on(GuiUpdatesListener.java:130) [SpectatorPlus-B3.0-SNAPSHOT.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:871) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at net.minecraft.server.v1_9_R1.PlayerList.disconnect(PlayerList.java:381) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1060) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at net.minecraft.server.v1_9_R1.NetworkManager.handleDisconnection(NetworkManager.java:317) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at net.minecraft.server.v1_9_R1.ServerConnection.c(ServerConnection.java:175) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:820) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.2.jar:git-Spigot-e6f93f4-ed60c01]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
[17:29:27 INFO]: AmauryPi left the game.
```

**Comment by pgmann** [comment]
Looks fun! So to confirm, trying to open a player's inventory does nothing visually, but logs "Inventory opened" and "Inventory closed"?

**Comment by AmauryCarrade** [comment]
Only for the inspector inventory. Others works well in 1.9. All works well in 1.8.8.
